from __future__ import annotations

import json
import os
from datetime import UTC, datetime
from pathlib import Path

import duckdb

DEMO_ROWS = (
    (
        "demo-001",
        "Lanterns at Low Tide",
        "Lanterns at Low Tide",
        "movie",
        1874,
        None,
        104,
        "Drama,Mystery",
        8.2,
        18420,
        False,
    ),
    (
        "demo-002",
        "The Ninth Observatory",
        "The Ninth Observatory",
        "movie",
        2018,
        None,
        128,
        "Adventure,Sci-Fi",
        7.8,
        12605,
        False,
    ),
    (
        "demo-003",
        "Salt Archive",
        "Salt Archive",
        "short",
        2024,
        None,
        18,
        "Documentary",
        8.7,
        904,
        False,
    ),
    (
        "demo-004",
        "Quiet Engines",
        "Quiet Engines",
        "movie",
        2016,
        None,
        96,
        "Drama",
        7.1,
        8412,
        False,
    ),
    (
        "demo-005",
        "Orchard of Satellites",
        "Orchard of Satellites",
        "tvSeries",
        2022,
        None,
        44,
        "Drama,Sci-Fi",
        8.5,
        29110,
        False,
    ),
    (
        "demo-006",
        "A Map of Ash",
        "A Map of Ash",
        "movie",
        2013,
        None,
        111,
        "History,Mystery",
        6.9,
        4450,
        False,
    ),
    (
        "demo-007",
        "Blue Hour Dispatch",
        "Blue Hour Dispatch",
        "podcastSeries",
        2020,
        None,
        36,
        "News",
        7.6,
        1160,
        False,
    ),
    (
        "demo-008",
        "The Glass Cartographer",
        "The Glass Cartographer",
        "movie",
        2025,
        None,
        119,
        "Fantasy",
        8.0,
        7302,
        False,
    ),
    (
        "demo-009",
        "Three Winters North",
        "Three Winters North",
        "tvMiniSeries",
        2019,
        2020,
        52,
        "Crime,Drama",
        7.9,
        15540,
        False,
    ),
    (
        "demo-010",
        "Signal Garden",
        "Signal Garden",
        "videoGame",
        2023,
        None,
        None,
        "Adventure",
        8.9,
        22201,
        False,
    ),
    (
        "demo-011",
        "After the Last Tram",
        "After the Last Tram",
        "short",
        2017,
        None,
        14,
        "Comedy,Drama",
        7.3,
        680,
        False,
    ),
    (
        "demo-012",
        "Moths in the Projector",
        "Moths in the Projector",
        "movie",
        2011,
        None,
        87,
        "Horror",
        6.6,
        5109,
        False,
    ),
    (
        "demo-013",
        "Borrowed Constellations",
        "Borrowed Constellations",
        "movie",
        2020,
        None,
        101,
        "Romance,Sci-Fi",
        7.7,
        13220,
        False,
    ),
    (
        "demo-014",
        "The Copper Season",
        "The Copper Season",
        "tvSeries",
        2015,
        2018,
        48,
        "Drama",
        8.1,
        19870,
        False,
    ),
    (
        "demo-015",
        "Museum of Small Weather",
        "Museum of Small Weather",
        "movie",
        2022,
        None,
        92,
        "Animation,Family",
        7.5,
        3820,
        False,
    ),
    (
        "demo-016",
        "Nocturne for Machines",
        "Nocturne for Machines",
        "short",
        2025,
        None,
        21,
        "Music,Sci-Fi",
        8.4,
        1442,
        False,
    ),
    (
        "demo-017",
        "Paper Kingdom Radio",
        "Paper Kingdom Radio",
        "podcastSeries",
        2021,
        None,
        31,
        "Comedy",
        7.2,
        940,
        False,
    ),
    (
        "demo-018",
        "The Long Way Through Noon",
        "The Long Way Through Noon",
        "movie",
        2009,
        None,
        123,
        "Adventure,Drama",
        7.0,
        6033,
        False,
    ),
    (
        "demo-019",
        "Stone Fruit Detective",
        "Stone Fruit Detective",
        "tvSeries",
        2024,
        None,
        42,
        "Comedy,Crime",
        8.3,
        9911,
        False,
    ),
    (
        "demo-020",
        "Wind Index",
        "Wind Index",
        "movie",
        2014,
        None,
        78,
        "Documentary",
        6.8,
        2301,
        False,
    ),
    (
        "demo-021",
        "Night Ferry Almanac",
        "Night Ferry Almanac",
        "movie",
        2019,
        None,
        108,
        "Drama,Thriller",
        7.6,
        11570,
        False,
    ),
    (
        "demo-022",
        "Axiom House",
        "Axiom House",
        "tvMiniSeries",
        2023,
        2023,
        57,
        "Mystery,Sci-Fi",
        8.6,
        17742,
        False,
    ),
    ("demo-023", "Dust Choir", "Dust Choir", "short", 2012, None, 16, "Music", 6.5, 412, False),
    (
        "demo-024",
        "The Weather Between Us",
        "The Weather Between Us",
        "movie",
        2024,
        None,
        114,
        "Drama,Romance",
        7.9,
        8704,
        False,
    ),
)


def build_demo_database(database_path: Path, *, force: bool = False) -> Path:
    if database_path.exists() and not force:
        return database_path

    database_path.parent.mkdir(parents=True, exist_ok=True)
    temporary = database_path.with_suffix(".building.duckdb")
    temporary.unlink(missing_ok=True)
    connection = duckdb.connect(str(temporary))
    try:
        connection.execute(
            """
            CREATE TABLE titles (
                imdb_id VARCHAR,
                primary_title VARCHAR,
                original_title VARCHAR,
                title_type VARCHAR,
                start_year INTEGER,
                end_year INTEGER,
                runtime_minutes INTEGER,
                genres VARCHAR,
                average_rating DOUBLE,
                num_votes BIGINT,
                is_adult BOOLEAN
            )
            """
        )
        connection.executemany(
            "INSERT INTO titles VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", DEMO_ROWS
        )
        connection.execute(
            """
            CREATE TABLE dataset_metadata (
                built_at TIMESTAMP,
                source_manifest JSON,
                row_count BIGINT
            )
            """
        )
        connection.execute(
            "INSERT INTO dataset_metadata VALUES (?, ?, ?)",
            [
                datetime.now(UTC).replace(tzinfo=None),
                json.dumps({"data_mode": "synthetic_demo", "source": "fictional"}),
                len(DEMO_ROWS),
            ],
        )
    finally:
        connection.close()
    os.replace(temporary, database_path)
    return database_path
